apiVersion: apps/v1
kind: Deployment
metadata:
  name: main-deployment
spec:
  replicas: 4
  selector:
    matchLabels:
      app: test-application
  template:
    metadata:
      labels:
        app: test-application
    spec:
      containers:
        - name: first-pod
          image: ux007893/k8s-deployment:tagname
          ports:
            - containerPort: 5000   # Matches your Dockerfile
