apiVersion: v1
kind: Service
metadata:
  name: vote
  namespace: default
  labels:
    app: vote
spec:
  type: ClusterIP
  selector:
    app: vote
  ports:
    - name: http
      protocol: TCP
      port: 5000        # cluster-visible port
      targetPort: 5000  # container port in pods

---
apiVersion: v1
kind: Service
metadata:
  name: shreeram
  namespace: default
  labels:
    app: shreeram
spec:
  type: ClusterIP
  selector:
    app: shreeram
  ports:
    - name: http
      protocol: TCP
      port: 5000
      targetPort: 5000
